name: Train CNN model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wandb seaborn

    - name: Configure WandB
      run: echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

    - name: Run training
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        pip install notebook
        jupyter nbconvert --to script cars-cnn.ipynb
        python cars-cnn.py

    - name: Save model artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: ./
